cat drupal-aca.yaml | sed -e "s/RESOURCE_GROUP/$RESOURCE_GROUP/g" \
-e "s/LOCATION/$LOCATION/g" \
-e "s/CONTAINER_APP_NAME/$CONTAINER_APP_NAME/g" \
-e "s/DRUPAL_DB_USER/$DRUPAL_DB_USER/g" \
-e "s/DRUPAL_DB_PASSWORD/$DRUPAL_DB_PASSWORD/g" \
-e "s/DRUPAL_DB_NAME/$DRUPAL_DB_NAME/g" \
-e "s/DRUPAL_DB_HOST/$DRUPAL_DB_HOST/g" \
-e "s/STORAGE_MOUNT_NAME/$STORAGE_MOUNT_NAME/g" \
-e "s|ENVIRONMENT_ID|$ENVIRONMENT_ID|g" \
-e "s|MIN_REPLICAS|$MIN_REPLICAS|g" \
-e "s|MAX_REPLICAS|$MAX_REPLICAS|g" \
> drupal-aca-DoNotCheckIn.yaml
